import {useState} from 'react'
import {Navigate,useLocation,useNavigate} from 'react-router-dom'
import {useStore} from '../store/useStore.js'
import {t} from '../lib/i18n.js'
import {programmeDefinitionOf,programmeProgressionOptions} from '../lib/programmes.js'
import {pickupRows,pickupTarget,startProgrammePickupInState,completedProgrammeDefinition,repeatProgrammePickupInState} from '../lib/programme-pickup.js'
import {POLICY_NAME} from '../lib/progression.js'
import {Button,Stepper,Segmented} from '../components/ui.jsx'
import Icon from '../components/Icon.jsx'
export default function ProgrammePickup(){
 const nav=useNavigate(),location=useLocation(),state=useStore(s=>s.S),update=useStore(s=>s.update)
 const repeatCycleId=location.state?.repeatCycleId
 const definition=repeatCycleId?completedProgrammeDefinition(state,repeatCycleId):programmeDefinitionOf(state,location.state?.programmeId)
 const [length,setLength]=useState(definition?.weeks.length || 1),[values,setValues]=useState({}),[weekModes,setWeekModes]=useState(definition?.weeks.map(week=>week.mode || 'normal') || [])
 const [loadMode,setLoadMode]=useState('highest'),[deloadPercent,setDeloadPercent]=useState(10)
 const [openWeek,setOpenWeek]=useState(-1)
 const [progression,setProgression]=useState(definition?.progression || 'off'),[error,setError]=useState('')
 if(!state.programmeMode)return <Navigate to='/plan' replace/>
 const rows=definition?pickupRows(state,definition,{progression}):[],active=state.programmes.cycles.some(cycle=>cycle.programmeId===definition?.id&&cycle.status==='active')
 const groups = [...new Set(rows.map(row=>row.routineId))].map(id=>({id,name:rows.find(row=>row.routineId===id).routineName,rows:rows.filter(row=>row.routineId===id)}))
 const start=()=>{try{let cycle;update(s=>{cycle=repeatCycleId?repeatProgrammePickupInState(s,repeatCycleId,{length,values,weekModes,progression,loadMode,deloadPercent}):startProgrammePickupInState(s,definition,{length,values,weekModes,progression,loadMode,deloadPercent})});nav('/home?cycle='+encodeURIComponent(cycle.id))}catch(error){setError(error.message)}}
 const changeLength=value=>{const count=Math.max(1,Math.min(52,Math.round(value)||1));setLength(count);setWeekModes(previous=>Array.from({length:count},(_,index)=>previous[index] || definition.weeks[index]?.mode || definition.weeks.at(-1)?.mode || 'normal'))}
 return <div className='narrow' data-testid='programme-pickup'>
  <div className='hdr'><div><h1>{t(repeatCycleId?'Repeat programme':'Start programme')}</h1><div className='sub'>{definition?.name || t('Programme')}</div></div><button className='iconbtn' aria-label={t('Close')} onClick={()=>nav('/plan')}><Icon name='xmark'/></button></div>
  {!definition?<div className='empty'>{t('Programme not found')}</div>:<>
   {active&&<p>{t('This programme already has an active cycle.')}</p>}
   <div className='card pickup-setup'><label className='small' htmlFor='pickup-progression'>{t('Progression')}</label><select id='pickup-progression' className='field' value={progression} onChange={event=>setProgression(event.target.value)}>{programmeProgressionOptions(definition.weeks,state).map(policy=><option key={policy} value={policy}>{t(POLICY_NAME[policy])}</option>)}</select><Stepper label={t('Number of weeks')} value={length} onChange={changeLength} decimal={false} unit={t('weeks')}/></div>
   <h4 className='sec'>{t('Starting load')}</h4><div data-testid='pickup-load-mode'><Segmented value={loadMode} onChange={setLoadMode} options={[{value:'highest',label:t('Highest working weight')},{value:'deload',label:t('Lighter restart')}]}/><div className='small dim' style={{margin:'10px 2px 14px',lineHeight:1.45}}>{t(repeatCycleId?'Create a new active cycle from the completed programme snapshot.':'Choose how the first week should load before you start.')}</div>{loadMode==='deload'&&<div className='card' style={{marginBottom:12}}><Stepper label={t('Deload percentage')} value={deloadPercent} unit='%' decimal={false} onChange={value=>setDeloadPercent(Math.max(1,Math.min(50,Math.round(value)||1)))}/></div>}</div>
   <details className='card pickup-weeks'><summary><strong>{t('Week modes')}</strong><span className='small dim'>{t('{0} weeks',length)} · {t('{0} deload',weekModes.filter(mode=>mode==='deload').length)} · {t('{0} rest',weekModes.filter(mode=>mode==='rest').length)}</span><Icon name='chevronDown'/></summary><div className='week-mode-list'>{weekModes.map((mode,index)=><div className='week-mode-row' data-week-mode={mode} key={index}><button type='button' className='week-mode-toggle' aria-expanded={openWeek===index} onClick={()=>setOpenWeek(current=>current===index?-1:index)}><strong>{t('Week')} {index+1}</strong><span className='tag'>{t(mode==='normal'?'Normal':mode==='deload'?'Deload':'Rest')}</span><Icon name={openWeek===index?'chevronUp':'chevronDown'}/></button>{openWeek===index&&<div className='week-mode-options'><Segmented value={mode} onChange={value=>setWeekModes(previous=>previous.map((entry,i)=>i===index?value:entry))} options={['normal','deload','rest'].map(value=>({value,label:t(value==='normal'?'Normal':value==='deload'?'Deload':'Rest')}))}/></div>}</div>)}</div></details>
   <div className='row' style={{justifyContent:'space-between',margin:'18px 0 8px',gap:8}}><h4 className='sec' style={{margin:0}}>{t('Exercise starting targets')}</h4><Button size='sm' variant='tinted' icon='sparkles' onClick={()=>setValues(Object.fromEntries(rows.map(row=>[row.key,loadMode==='deload'?pickupTarget(row,{loadMode,deloadPercent}):row.suggestion])))}>{t('Apply all')}</Button></div>
   <div className='pickup-routine-list'>{groups.map(group=><details className='card pickup-routine' key={group.id} data-pickup-routine={group.id}><summary><span className='grow'><strong>{group.name}</strong><span className='small dim'>{t('{0} exercises',group.rows.length)}</span></span><Icon name='chevronDown'/></summary><div className='pickup-target-list'>{group.rows.map(row=>{const suggested=loadMode==='deload'?pickupTarget(row,{loadMode,deloadPercent}):row.suggestion;return <div className='pickup-target-row' data-pickup-key={row.key} key={row.key}><div className='pickup-target-main'><strong>{row.name}</strong><Stepper ariaLabel={group.name+' · '+row.name+' · '+t('Target')+' ('+row.unit+')'} value={pickupTarget(row,{loadMode,deloadPercent,values})} step={row.step} unit={row.unit} onChange={value=>setValues(previous=>({...previous,[row.key]:value}))}/></div><div className='pickup-target-hint'><span className='small dim'>{row.field==='weight'?t('Previous best:')+' '+row.best+' '+row.unit+' · ':''}{t('Suggested: {0} {1}',suggested,row.unit)}</span><Button size='sm' variant='ghost' aria-label={t('Use suggestion')+' · '+row.name} onClick={()=>setValues(previous=>({...previous,[row.key]:suggested}))}>{t('Apply')}</Button></div>{row.estimate>0&&<div className='small dim'>{t('1RM ~{0} {1}',row.estimate,row.unit)} · {t('target {0} reps',row.targetReps)}</div>}</div>})}</div></details>)}</div>
   {error&&<p role='alert'>{error}</p>}<Button variant='primary' icon='play' style={{width:'100%',marginTop:16}} disabled={active||!rows.length} onClick={start}>{t('Start cycle')}</Button>
  </>}
 </div>
}
